//#include "PremierNvramDescr.h"
//
//static NVRAM_TABLE_ROW short_table_locations[]=
//{
//    // DO NOT REMOVE NEXT LINE!!!
//    HAT_GAME_DESCRIPTIONS_SHORT
//
// 	,{NVRAM_SAP_HITS_3THREE_FISH				,		16,		64, HAT_GAME_HEADER_LENGTH_SHORT + 0}
//	,{NVRAM_SAP_HITS_4FOUR_FISH					,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 16}
//	,{NVRAM_SAP_HITS_5FIVE_FISH					,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 32}
//	,{NVRAM_SAP_HITS_3THREE_DOLPHIN				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 48}
//	,{NVRAM_SAP_HITS_4FOUR_DOLPHIN				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 64}
//	,{NVRAM_SAP_HITS_5FIVE_DOLPHIN				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 80}
//	,{NVRAM_SAP_HITS_3THREE_WHALE				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 96}
//	,{NVRAM_SAP_HITS_4FOUR_WHALE				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 112}
//	,{NVRAM_SAP_HITS_5FIVE_WHALE				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 128}
//	,{NVRAM_SAP_HITS_2TWO_CORAL					,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 144}
//	,{NVRAM_SAP_HITS_3THREE_CORAL				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 160}
//	,{NVRAM_SAP_HITS_4FOUR_CORAL				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 176}
//	,{NVRAM_SAP_HITS_5FIVE_CORAL				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 192}
//	,{NVRAM_SAP_HITS_3THREE_ISLAND				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 208}
//	,{NVRAM_SAP_HITS_4FOUR_ISLAND				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 224}
//	,{NVRAM_SAP_HITS_5FIVE_ISLAND				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 240}
//	,{NVRAM_SAP_HITS_3THREE_SCATTER				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 256}
//	,{NVRAM_SAP_HITS_BONUS_FREE_SPINS			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 272}
//	,{NVRAM_SAP_TOTAL_FREE_SPINS				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 288}
//	,{NVRAM_SAP_TOTAL_MULTIPLIER				,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 304}
//	,{NVRAM_SAP_WINS_3THREE_FISH				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 320}
//	,{NVRAM_SAP_WINS_4FOUR_FISH					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 352}
//	,{NVRAM_SAP_WINS_5FIVE_FISH					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 384}
//	,{NVRAM_SAP_WINS_3THREE_DOLPHIN				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 416}
//	,{NVRAM_SAP_WINS_4FOUR_DOLPHIN				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 448}
//	,{NVRAM_SAP_WINS_5FIVE_DOLPHIN				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 480}
//	,{NVRAM_SAP_WINS_3THREE_WHALE				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 512}
//	,{NVRAM_SAP_WINS_4FOUR_WHALE				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 544}
//	,{NVRAM_SAP_WINS_5FIVE_WHALE				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 576}
//	,{NVRAM_SAP_WINS_2TWO_CORAL					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 608}
//	,{NVRAM_SAP_WINS_3THREE_CORAL				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 640}
//	,{NVRAM_SAP_WINS_4FOUR_CORAL				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 672}
//	,{NVRAM_SAP_WINS_5FIVE_CORAL				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 704}
//	,{NVRAM_SAP_WINS_3THREE_ISLAND				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 736}
//	,{NVRAM_SAP_WINS_4FOUR_ISLAND				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 768}
//	,{NVRAM_SAP_WINS_5FIVE_ISLAND				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 800}
//	,{NVRAM_SAP_WINS_3THREE_SCATTER				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 832}
//	,{NVRAM_SAP_WINS_BONUS_FREE_SPINS			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 864}
//	,{NVRAM_SAPHITWIN_CRC						,		4,		192, HAT_GAME_HEADER_LENGTH_SHORT + 896}
//	,{NVRAM_SAP_LAST_HITS_3THREE_FISH			,		16,		64, HAT_GAME_HEADER_LENGTH_SHORT + 900}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_FISH			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 916}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_FISH			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 932}
//	,{NVRAM_SAP_LAST_HITS_3THREE_DOLPHIN		,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 948}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_DOLPHIN			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 964}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_DOLPHIN			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 980}
//	,{NVRAM_SAP_LAST_HITS_3THREE_WHALE			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 996}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_WHALE			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1012}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_WHALE			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1028}
//	,{NVRAM_SAP_LAST_HITS_2TWO_CORAL			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1044}
//	,{NVRAM_SAP_LAST_HITS_3THREE_CORAL			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1060}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_CORAL			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1076}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_CORAL			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1092}
//	,{NVRAM_SAP_LAST_HITS_3THREE_ISLAND			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1108}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_ISLAND			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1124}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_ISLAND			,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1140}
//	,{NVRAM_SAP_LAST_HITS_3THREE_SCATTER		,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1156}
//	,{NVRAM_SAP_LAST_HITS_BONUS_FREE_SPINS		,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1172}
//	,{NVRAM_SAP_LAST_FREE_SPINS					,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1188}
//	,{NVRAM_SAP_LAST_MULTIPLIER					,		16,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1204}
//	,{NVRAM_SAP_LAST_WINS_3THREE_FISH			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1220}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_FISH			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1252}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_FISH			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1284}
//	,{NVRAM_SAP_LAST_WINS_3THREE_DOLPHIN		,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1316}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_DOLPHIN			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1348}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_DOLPHIN			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1380}
//	,{NVRAM_SAP_LAST_WINS_3THREE_WHALE			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1412}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_WHALE			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1444}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_WHALE			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1476}
//	,{NVRAM_SAP_LAST_WINS_2TWO_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1508}
//	,{NVRAM_SAP_LAST_WINS_3THREE_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1540}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1572}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1604}
//	,{NVRAM_SAP_LAST_WINS_3THREE_ISLAND			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1636}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_ISLAND			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1668}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_ISLAND			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1700}
//	,{NVRAM_SAP_LAST_WINS_3THREE_SCATTER		,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1732}
//	,{NVRAM_SAP_LAST_WINS_BONUS_FREE_SPINS		,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1764}
//	,{NVRAM_SAPHITWIN_CRC						,		4,		192, HAT_GAME_HEADER_LENGTH_SHORT + 1796}
//
//    // DO NOT REMOVE ABOVE LINE!!!
//};
//
//static NVRAM_TABLE_ROW long_table_locations[]=
//{
//    // DO NOT REMOVE NEXT LINE!!!
//    HAT_GAME_DESCRIPTIONS_LONG
//
// 	,{NVRAM_SAP_HITS_3THREE_FISH				,		32,		64, HAT_GAME_HEADER_LENGTH_SHORT + 0}
//	,{NVRAM_SAP_HITS_4FOUR_FISH					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 32}
//	,{NVRAM_SAP_HITS_5FIVE_FISH					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 64}
//	,{NVRAM_SAP_HITS_3THREE_DOLPHIN				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 96}
//	,{NVRAM_SAP_HITS_4FOUR_DOLPHIN				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 128}
//	,{NVRAM_SAP_HITS_5FIVE_DOLPHIN				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 160}
//	,{NVRAM_SAP_HITS_3THREE_WHALE				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 192}
//	,{NVRAM_SAP_HITS_4FOUR_WHALE				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 224}
//	,{NVRAM_SAP_HITS_5FIVE_WHALE				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 256}
//	,{NVRAM_SAP_HITS_2TWO_CORAL					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 288}
//	,{NVRAM_SAP_HITS_3THREE_CORAL				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 320}
//	,{NVRAM_SAP_HITS_4FOUR_CORAL				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 352}
//	,{NVRAM_SAP_HITS_5FIVE_CORAL				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 384}
//	,{NVRAM_SAP_HITS_3THREE_ISLAND				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 416}
//	,{NVRAM_SAP_HITS_4FOUR_ISLAND				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 448}
//	,{NVRAM_SAP_HITS_5FIVE_ISLAND				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 480}
//	,{NVRAM_SAP_HITS_3THREE_SCATTER				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 512}
//	,{NVRAM_SAP_HITS_BONUS_FREE_SPINS			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 544}
//	,{NVRAM_SAP_TOTAL_FREE_SPINS				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 576}
//	,{NVRAM_SAP_TOTAL_MULTIPLIER				,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 608}
//	,{NVRAM_SAP_WINS_3THREE_FISH				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 640}
//	,{NVRAM_SAP_WINS_4FOUR_FISH					,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 704}
//	,{NVRAM_SAP_WINS_5FIVE_FISH					,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 768}
//	,{NVRAM_SAP_WINS_3THREE_DOLPHIN				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 832}
//	,{NVRAM_SAP_WINS_4FOUR_DOLPHIN				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 896}
//	,{NVRAM_SAP_WINS_5FIVE_DOLPHIN				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 960}
//	,{NVRAM_SAP_WINS_3THREE_WHALE				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1024}
//	,{NVRAM_SAP_WINS_4FOUR_WHALE				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1088}
//	,{NVRAM_SAP_WINS_5FIVE_WHALE				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1152}
//	,{NVRAM_SAP_WINS_2TWO_CORAL					,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1216}
//	,{NVRAM_SAP_WINS_3THREE_CORAL				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1280}
//	,{NVRAM_SAP_WINS_4FOUR_CORAL				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1344}
//	,{NVRAM_SAP_WINS_5FIVE_CORAL				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1408}
//	,{NVRAM_SAP_WINS_3THREE_ISLAND				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1472}
//	,{NVRAM_SAP_WINS_4FOUR_ISLAND				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1536}
//	,{NVRAM_SAP_WINS_5FIVE_ISLAND				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1600}
//	,{NVRAM_SAP_WINS_3THREE_SCATTER				,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1664}
//	,{NVRAM_SAP_WINS_BONUS_FREE_SPINS			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1728}
//	,{NVRAM_SAPHITWIN_CRC						,		4,		192, HAT_GAME_HEADER_LENGTH_SHORT + 1792}
//	,{NVRAM_SAP_LAST_HITS_3THREE_FISH			,		32,		64, HAT_GAME_HEADER_LENGTH_SHORT + 1796}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_FISH			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1828}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_FISH			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1860}
//	,{NVRAM_SAP_LAST_HITS_3THREE_DOLPHIN		,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1892}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_DOLPHIN			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1924}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_DOLPHIN			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1956}
//	,{NVRAM_SAP_LAST_HITS_3THREE_WHALE			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 1988}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_WHALE			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2020}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_WHALE			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2052}
//	,{NVRAM_SAP_LAST_HITS_2TWO_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2084}
//	,{NVRAM_SAP_LAST_HITS_3THREE_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2116}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2148}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_CORAL			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2180}
//	,{NVRAM_SAP_LAST_HITS_3THREE_ISLAND			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2212}
//	,{NVRAM_SAP_LAST_HITS_4FOUR_ISLAND			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2244}
//	,{NVRAM_SAP_LAST_HITS_5FIVE_ISLAND			,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2276}
//	,{NVRAM_SAP_LAST_HITS_3THREE_SCATTER		,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2308}
//	,{NVRAM_SAP_LAST_HITS_BONUS_FREE_SPINS		,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2340}
//	,{NVRAM_SAP_LAST_FREE_SPINS					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2372}
//	,{NVRAM_SAP_LAST_MULTIPLIER					,		32,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2404}
//	,{NVRAM_SAP_LAST_WINS_3THREE_FISH			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2436}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_FISH			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2500}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_FISH			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2564}
//	,{NVRAM_SAP_LAST_WINS_3THREE_DOLPHIN		,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2628}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_DOLPHIN			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2692}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_DOLPHIN			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2756}
//	,{NVRAM_SAP_LAST_WINS_3THREE_WHALE			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2820}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_WHALE			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2884}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_WHALE			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 2948}
//	,{NVRAM_SAP_LAST_WINS_2TWO_CORAL			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3012}
//	,{NVRAM_SAP_LAST_WINS_3THREE_CORAL			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3076}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_CORAL			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3140}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_CORAL			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3204}
//	,{NVRAM_SAP_LAST_WINS_3THREE_ISLAND			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3268}
//	,{NVRAM_SAP_LAST_WINS_4FOUR_ISLAND			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3332}
//	,{NVRAM_SAP_LAST_WINS_5FIVE_ISLAND			,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3396}
//	,{NVRAM_SAP_LAST_WINS_3THREE_SCATTER		,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3460}
//	,{NVRAM_SAP_LAST_WINS_BONUS_FREE_SPINS		,		64,		0, HAT_GAME_HEADER_LENGTH_SHORT + 3524}
//	,{NVRAM_SAPHITWIN_CRC						,		4,		192, HAT_GAME_HEADER_LENGTH_SHORT + 3588}
//
//    // DO NOT REMOVE ABOVE LINE!!!
//};
